Use internal memory in if_then_else when possible
SSoelvsten/adiar pull request #290
Opened 2022-03-08 18:23 UTC by AnnaBlume99

Yet another part of #98

2022-03-10 07:54 UTC, SSoelvsten requested changes
Looks good. Here are tiny nitpicks.

- Add the `__` prefix to the if-then-else helper functions
- Rebase all commits into a single one.

Furthermore, I also found a little thing to improve in my code. This could then be a small second commit.

2022-03-10 07:54 UTC, SSoelvsten commented on src/adiar/bdd/if_then_else.cpp
> +  inline void ite_resolve_request(pq_1_t &ite_pq_1,
Add the `__` prefix for consistency.

2022-03-10 07:54 UTC, SSoelvsten commented on src/adiar/bdd/if_then_else.cpp
> +    }
Not your fault, since this is my code. But, now that you are at it with this file, would you please

- Move this conditional above line 504
- Add the `__` prefix to `ite_zip_bdds`

2022-03-10 14:10 UTC, AnnaBlume99 commented on src/adiar/bdd/if_then_else.cpp
> +    }
It's not possible since the conditional uses v_then which is defined after 504. But I can put it at 507

2022-03-11 11:22 UTC, SSoelvsten commented on src/adiar/bdd/if_then_else.cpp
> +    }
Ah, that's why I did it like that. Thanks for clarifying. :+1:

2022-03-11 11:34 UTC, SSoelvsten requested changes
The zipping if-statement actually should not be moved - the fact it can actually is indicative of a bug ( moved to #295 )

2022-03-11 11:34 UTC, SSoelvsten commented on src/adiar/bdd/if_then_else.cpp
> +    node_t v_else = in_nodes_else.pull();
I think here actually is a bug of mine. The condition on *511* should be on `v_else` not on `v_then` once more.
- Add a unit test where one should **not** zip because of the *then* case is not beyond the max_label of `bdd_if`
- Add a unit test where one should **not** zip because of the *else* case is not beyond the max_label of `bdd_if` (this one should break)
- Swap back the order between opening the `in_nodes_else` and this if-statement
- Fix the bug by comparing with `label_of(v_else)` instead.

Alternatively, place this into a *BUG* issue. And solve it after merging this back in.

2022-03-11 12:27 UTC, SSoelvsten commented on src/adiar/bdd/if_then_else.cpp
> +    node_t v_else = in_nodes_else.pull();
Moved to #295 .

2022-03-13 09:45 UTC, SSoelvsten approved these changes

2022-03-14 11:09 UTC, merged