Unbucketed levelized priority queue
SSoelvsten/adiar pull request #347
Opened 2022-06-15 13:31 UTC by AnnaBlume99

2022-06-15 16:22 UTC, SSoelvsten requested changes
Very good first draft! :slightly_smiling_face:

2022-06-15 16:22 UTC, SSoelvsten commented on src/adiar/internal/pred.h
> +    if(max_pq1_size <= no_lookahead_bound(2)) {
This `2` should be given by the policy. If it is the policy used for equality checking, then the *1* lookahead bound is more correct.

2022-06-15 16:22 UTC, SSoelvsten commented on src/adiar/statistics.cpp
>        << stats.lpq.internal << " = " << percent_frac(stats.lpq.internal, total_lpqs) << percent << endl;
When printing statistics, it would be better to know:
1. How much was in internal memory (`stats.lpq.unbucketed + stats.lpq.internal` out of `total_lpqs`)?
2. How much was the internal runs without buckets (`stats.lpq.unbucketed` out of `stats.lpq.unbucketed + stats.lpq.internal`)?

2022-06-15 16:22 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +    return result;
separate `return` is not really needed.

2022-06-15 16:22 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +            label_t  LOOK_AHEAD = ADIAR_LPQ_LOOKAHEAD,
I'd either place it as the very first argument or after the `elem` arguments.

2022-06-15 16:22 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +        + label_merger<file_t, level_comp_t, FILES>::memory_usage();
Remove `label_merger` memory usage, since it is not in here.

2022-06-15 16:22 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +        ::memory_fits((memory_bytes - const_memory_bytes) / DATA_STRUCTURES);
Since there are no sorters this hack is not necessary. Just return what the `internal_priority_queue` can fit.

2022-06-15 16:22 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +    tpie::memory_size_type _memory_occupied_by_priority_queue;
This was only necessary for the buckets memory computations. This should be possible to remove, since all memory is used by the priority queue.

2022-06-15 16:22 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +      return std::max(eight_MiB, memory_given);
`memory_given` should in pretty much all cases be larger than 8 MiB. There is no need to increase it. In fact, I should fix this to only be whenever the type of the priority queue is the *external* memory variant.

2022-06-15 16:22 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +    }
Remove?

2022-06-15 16:22 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +    }
This would crash if `_priority_queue.empty()`?

2022-06-15 16:22 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +      return has_next_level();
Or just `return true`.

2022-06-15 16:22 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +      //   Set the level to be the next from the queue, and forward the level_merger
Remove: "and forward the level_merger"

2022-06-16 06:48 UTC, SSoelvsten commented on src/adiar/statistics.cpp
> +      << stats.lpq.internal << " = " << percent_frac(stats.lpq.unbucketed, total_lpqs) << percent << endl;
`stats.lpq.internal` is still printed here.

2022-06-16 08:42 UTC, SSoelvsten commented
Here are a few statistics on how much the unbucketed priority queue was used in the Picotrav benchmark.

| arithmetic/adder | arithmetic/sin | random_control/cavlc | random_control/ctrl.blif |
|-----------------------|-------------------|------------------------------|--------------------------------|
| 88.9%                | 12.96%          | 90.65%                       | 99.64%                         |

With the Queens problem, we have

| 4           | 5            | 6    |
|------------|------------|------|
| 26.67% | 20.83% | 0% |

So best are *ctrl* and *cavlc* for testing the performance differenc. Possible, also look at *adder*.

2022-06-16 11:46 UTC, SSoelvsten commented
Even for the *ctrl* benchmark we do only really see a ~3% performance increase .

2022-07-04 11:13 UTC, AnnaBlume99 commented on src/adiar/internal/levelized_priority_queue.h
> +            label_t  LOOK_AHEAD = ADIAR_LPQ_LOOKAHEAD,
This is not possible, because it needs to come after the arguments that have no default, but be the first default argument

2022-07-06 11:09 UTC, SSoelvsten requested changes
Tiny nitpicks left.

2022-07-06 11:09 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +  inline bool level_cmp_lt(const label_t l1, const label_t l2, level_comp_t level_comp)
The `level_comp` should be a reference, such that it is not using the copy-constructor.

2022-07-06 11:09 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +  inline bool level_cmp_le(const label_t l1, const label_t l2, level_comp_t level_comp)
The `level_comp` should be a reference, such that it is not using the copy-constructor.

2022-07-06 11:09 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +            label_t  LOOK_AHEAD = ADIAR_LPQ_LOOKAHEAD,
Hmm, then I'd either (a) move it after `elem_comp_t` or make it a non-default argument.

2022-07-06 11:09 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +                  "There should be a next level to go to");
Assuming the `!has_current_level() || empty_level()` is this not equivalent to `!empty`?

2022-07-06 11:09 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +      label_t next_label_from_queue = elem_level_t::label_of(_priority_queue.top());
given that `empty_level()` must be true, then this can be replaced with `next_level()`, I believe.

2022-07-06 11:09 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +            label_t  LOOK_AHEAD = ADIAR_LPQ_LOOKAHEAD,
Hmm, then I'd either (a) move it after `elem_comp_t` or make it a non-defaulted argument.

2022-07-06 12:08 UTC, AnnaBlume99 commented on src/adiar/internal/levelized_priority_queue.h
> +            label_t  LOOK_AHEAD = ADIAR_LPQ_LOOKAHEAD,
It will be moved after elem_comp_t. We almost always use the standard lookahead and it seems odd to always have to specify this

2022-07-07 07:47 UTC, SSoelvsten requested changes
A few more nitpicks.

- There are quite a few functions that can be made `const`, I believe.
- I looked through the unit tests and found a few things to tidy up. Also, they seem to be out-of-order. Is that just the order they were in initially or can they be sorted?

2022-07-07 07:47 UTC, SSoelvsten commented on src/adiar/internal/intercut.h
> +    } else*/ if(max_pq_size <= pq_1_memory_fits && max_pq_size <= pq_2_memory_fits) {
If #362 is merged first, then when rebasing on-top have this uncommented again.

2022-07-07 07:47 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +      return internal_priority_queue<elem_t, elem_comp_t>::memory_fits(memory_bytes / DATA_STRUCTURES);
I believe the `/ DATA_STRUCTURES` semantically makes little sense (it works of course, because *DATA_STRUCTURES* is equals to 1): should the `memory_fits` of the internal_priority_queue not be able to deal with the number of data structures within itself?

2022-07-07 07:47 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +    bool has_next_level() /*const*/
This probably can be made `const`, given that the `.empty()` and the `.top()` functions can be *const*?

2022-07-07 07:47 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +    label_t next_level() /*const*/
I believe, this can be made `const`?

2022-07-07 07:47 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +      return result;
Maybe turn this into a one-liner?

2022-07-07 07:47 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +    bool can_push() /*const*/
Definitely `const`

2022-07-07 07:47 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +    bool empty_level()
Could this be `const`?

2022-07-07 07:47 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +    bool can_pull()
If `.empty_level()` can be made `const` then this one too.

2022-07-07 07:47 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +    elem_t top()
Can be made `const`.

2022-07-07 07:47 UTC, SSoelvsten commented on src/adiar/internal/levelized_priority_queue.h
> +    elem_t peek()
Can be made `const`.

2022-07-07 07:47 UTC, SSoelvsten commented on test/adiar/internal/test_levelized_priority_queue.cpp
> +        });
Remove: this unit test is equivalent to *forwards to first level*

2022-07-07 07:47 UTC, SSoelvsten commented on test/adiar/internal/test_levelized_priority_queue.cpp
> +        it("forwards to first level", [&]() {
Rename: *forwards to stop level [1]*

2022-07-07 07:47 UTC, SSoelvsten commented on test/adiar/internal/test_levelized_priority_queue.cpp
> +        it("forwards to second level", [&]() {
Rename: *forwards to next level with content [1]*

2022-07-07 07:47 UTC, SSoelvsten commented on test/adiar/internal/test_levelized_priority_queue.cpp
> +        });
Remove: this is equivalent to *forwards to second level*

2022-07-07 07:47 UTC, SSoelvsten commented on test/adiar/internal/test_levelized_priority_queue.cpp
> +        it("forwards to stop level", [&]() {
Rename: *forwards to stop level [2]*

2022-07-07 07:47 UTC, SSoelvsten commented on test/adiar/internal/test_levelized_priority_queue.cpp
> +        it("forwards to first level for unknown level prior to second level", [&]() {
Rename: *forwards to unknown level without content [1]*

2022-07-07 07:47 UTC, SSoelvsten commented on test/adiar/internal/test_levelized_priority_queue.cpp
> +        it("forwards past unknown level", [&]() {
Rename: *forwards to unknown level without content [2]*

2022-07-07 07:47 UTC, SSoelvsten commented on test/adiar/internal/test_levelized_priority_queue.cpp
> +          pq.setup_next_level(); // read: 5
`// 5`

2022-07-07 10:47 UTC, AnnaBlume99 commented on src/adiar/internal/levelized_priority_queue.h
> +    bool has_next_level() /*const*/
No unfortunately. Something with the label_of() function prevents it from being const

2022-07-07 10:47 UTC, AnnaBlume99 commented on src/adiar/internal/levelized_priority_queue.h
> +    label_t next_level() /*const*/
Same as for has_next_level()

2022-07-07 10:48 UTC, AnnaBlume99 commented on src/adiar/internal/levelized_priority_queue.h
> +    bool empty_level()
Same as for has_next_level()

2022-07-07 10:51 UTC, AnnaBlume99 commented on src/adiar/internal/levelized_priority_queue.h
> +    elem_t top()
No because the debug statement uses can_pull() which uses empty()

2022-07-07 10:51 UTC, AnnaBlume99 commented on src/adiar/internal/levelized_priority_queue.h
> +    elem_t peek()
Cannot be made const because top() cannot

2022-07-07 10:51 UTC, AnnaBlume99 commented on src/adiar/internal/levelized_priority_queue.h
> +    bool can_pull()
Same as for has_next_level()

2022-07-12 11:18 UTC, SSoelvsten requested changes
Quite a lot got messed up when rebasing on *main*.

- [ ] There are merge conflicts in *internal/intercut.h* in commit 2404130b717055ef80bada8578ee8956598ef32c
- [ ] Commit cb38e8a73d2d06553d3f9043f8c01b8afdb5e792 includes changes to *test_levelized_priority_queue* that have nothing to do with fixing the intercut size bound.

Furthermore, there is a tiny problem with the *+2* in the intercut size bound.

2022-07-12 11:18 UTC, SSoelvsten commented on src/adiar/internal/intercut.h
> +    return to_size(3 * ((intercut_policy::mult_factor * max_1level_cut) + 2u) / 2);
The +2 should be outside of the 3/2 .

2022-07-12 11:18 UTC, SSoelvsten commented on src/adiar/internal/intercut.h
> +>>>>>>> 6dffa4d (Remove _level_merger)
Lingering merge conflict inside of a commit

2022-07-12 11:18 UTC, SSoelvsten commented on src/adiar/internal/intercut.h
> +>>>>>>> a6f4a4d (Make algorithms use the new LPQ when input is small)
Lingering merge conflict!

2022-07-12 11:18 UTC, SSoelvsten commented on src/adiar/internal/intercut.h
> +>>>>>>> a6f4a4d (Make algorithms use the new LPQ when input is small)
Lingering merge conflict

2022-07-12 11:18 UTC, SSoelvsten commented on src/adiar/internal/intercut.h
> +>>>>>>> a6f4a4d (Make algorithms use the new LPQ when input is small)
Lingering merge conflict!

2022-07-13 14:06 UTC, SSoelvsten approved these changes

2022-07-14 07:56 UTC, SSoelvsten approved these changes

2022-07-14 10:38 UTC, merged